FROM ubuntu:20.04

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

RUN mkdir build && \
    cd build && \
    cmake .. && \
    make -j4

EXPOSE 9092

CMD ["./build/hyperq-broker","1","/va/log/hypperq"]